// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://letmquczppyhxtzixyfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldG1xdWN6cHB5aHh0eml4eWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDA1MTgsImV4cCI6MjA2MzY3NjUxOH0.dXft8CliL9vaqWGqUHmnFV4uW1MfrNqotC2em1Cij_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);